//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thermostat {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Relay X1 module using socket H4 of hubAP5.</summary>
        private Gadgeteer.Modules.GHIElectronics.Relay_X1 Heat;
        
        /// <summary>The Relay X1 module using socket H5 of hubAP5.</summary>
        private Gadgeteer.Modules.GHIElectronics.Relay_X1 Cool;
        
        /// <summary>The Relay X1 module using socket H6 of hubAP5.</summary>
        private Gadgeteer.Modules.GHIElectronics.Relay_X1 Fan;
        
        /// <summary>The TemperatureHumidity module using socket H3 of hubAP5.</summary>
        private Gadgeteer.Modules.Seeed.TemperatureHumidity temperatureHumidity;
        
        /// <summary>The WiFi_RS21 (Premium) module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.WiFi_RS21 wifi_RS21;
        
        /// <summary>The Display_CP7 module using sockets 15, 16, 17 and 14 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Display_CP7 Display;
        
        /// <summary>The HubAP5 module using socket 12 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.HubAP5 hubAP5;
        
        /// <summary>The Barometer module using socket 10 of the mainboard.</summary>
        private Gadgeteer.Modules.Seeed.Barometer barometer;
        
        /// <summary>The SD2405 Real-Time Clock module using socket 13 of the mainboard.</summary>
        private Gadgeteer.Modules.DFRobot.SD2405_Real_Time_Clock RealTimeClock;
        
        /// <summary>The SDCard module using socket 9 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.SDCard sdCard;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZRaptor Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZRaptor)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZRaptor();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.hubAP5 = new GTM.GHIElectronics.HubAP5(12);
            this.Heat = new GTM.GHIElectronics.Relay_X1(this.hubAP5.HubSocket4);
            this.Cool = new GTM.GHIElectronics.Relay_X1(this.hubAP5.HubSocket5);
            this.Fan = new GTM.GHIElectronics.Relay_X1(this.hubAP5.HubSocket6);
            this.temperatureHumidity = new GTM.Seeed.TemperatureHumidity(this.hubAP5.HubSocket3);
            this.wifi_RS21 = new GTM.GHIElectronics.WiFi_RS21(3);
            this.Display = new GTM.GHIElectronics.Display_CP7(15, 16, 17, 14);
            this.barometer = new GTM.Seeed.Barometer(10);
            this.RealTimeClock = new GTM.DFRobot.SD2405_Real_Time_Clock(13);
            this.sdCard = new GTM.GHIElectronics.SDCard(9);
        }
    }
}
