//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thermostat
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("Thermostat.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static Microsoft.SPOT.Font GetFont(Resources.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(Resources.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static byte[] GetBytes(Resources.BinaryResources id)
        {
            return ((byte[])(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            AutoDown = -25572,
            BackGround = -24726,
            ArrowKeyDown = -14715,
            CoolDown = -13717,
            PowerOffDown = -11541,
            HeatDisabled = -4803,
            CoolEnabled = -124,
            PowerOffEnabled = 49,
            FanDown = 171,
            ArrowKeyUp = 1218,
            CoolDisabled = 2160,
            AutoEnabled = 9956,
            HeatEnabled = 14594,
            FanDisabled = 16231,
            AutoDisabled = 16580,
            FanEnabled = 23204,
            PowerOffDisabled = 23496,
            HeatDown = 24537,
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            small = 13070,
            NinaB = 18060,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            ControlScreen = 28913,
        }
    }
}
